# Generated by Django 5.1.15 on 2026-04-02 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_preferences_mfa'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='accounts_no_user_id_b29cd4_idx',
            old_name='accounts_not_user_id_97fcb7_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='accounts_no_notific_681bde_idx',
            old_name='accounts_not_notific_b1ca7f_idx',
        ),
    ]
