# Generated by Django 5.1.15 on 2026-04-05 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_first_post_share_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbadge',
            name='code',
            field=models.CharField(choices=[('profile_ready', 'Profile Ready'), ('first_steps', 'First Steps'), ('first_post', 'First Post'), ('first_comment', 'First Comment'), ('first_referral', 'First Referral'), ('crew_builder', 'Crew Builder'), ('challenge_accepted', 'Challenge Accepted'), ('momentum', 'Momentum')], max_length=32),
        ),
    ]
