# Generated by Django 5.1.15 on 2026-04-06 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_birth_date_user_country_user_preferred_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allow_nsfw_content',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='banner',
            field=models.ImageField(blank=True, upload_to='profile_banners/'),
        ),
    ]
