# Generated by Django 5.1.15 on 2026-04-06 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_user_city_user_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('post_reply', 'Post Reply'), ('comment_reply', 'Comment Reply'), ('mention', 'Mention'), ('followed_user_joined', 'Followed User Joined'), ('challenge_started', 'Challenge Started')], max_length=32),
        ),
    ]
