# Generated by Django 5.1.15 on 2026-04-05 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedpost',
            name='status',
            field=models.CharField(choices=[('unread', 'Unread'), ('reading', 'Reading'), ('done', 'Done')], default='unread', max_length=12),
        ),
    ]
