# Generated by Django 5.1.15 on 2026-03-31 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_initial'),
        ('moderation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modaction',
            name='action_type',
            field=models.CharField(choices=[('remove_post', 'Remove Post'), ('approve_post', 'Approve Post'), ('remove_comment', 'Remove Comment'), ('approve_comment', 'Approve Comment'), ('lock_post', 'Lock Post'), ('sticky_post', 'Sticky Post'), ('ban_user', 'Ban User'), ('unban_user', 'Unban User'), ('agent_flag', 'Agent Flag'), ('agent_remove', 'Agent Remove'), ('agent_warn', 'Agent Warn')], max_length=30),
        ),
        migrations.CreateModel(
            name='CommunityAgentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_remove_threshold', models.FloatField(default=0.9)),
                ('allow_auto_remove', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('community', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_settings', to='communities.community')),
            ],
        ),
    ]
