# Generated by Django 5.1.15 on 2026-04-05 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0004_expand_post_mod_actions'),
    ]

    operations = [
        migrations.AddField(
            model_name='modmail',
            name='context_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='modmail',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('awaiting_mod', 'Awaiting mod'), ('awaiting_user', 'Awaiting user'), ('closed', 'Closed')], default='open', max_length=16),
        ),
    ]
