# Generated by Django 5.1.15 on 2026-04-06 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0005_modmail_context_json_modmail_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-created_at']},
        ),
    ]
