# Generated by Django 5.1.15 on 2026-03-31 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=5000)),
                ('sidebar_md', models.TextField(blank=True)),
                ('sidebar_html', models.TextField(blank=True)),
                ('icon', models.ImageField(blank=True, upload_to='community_icons/')),
                ('banner', models.ImageField(blank=True, upload_to='community_banners/')),
                ('community_type', models.CharField(choices=[('public', 'Public'), ('restricted', 'Restricted'), ('private', 'Private')], default='public', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subscriber_count', models.PositiveIntegerField(default=0)),
                ('allow_text_posts', models.BooleanField(default=True)),
                ('allow_link_posts', models.BooleanField(default=True)),
                ('allow_image_posts', models.BooleanField(default=True)),
                ('allow_polls', models.BooleanField(default=False)),
                ('vote_hide_minutes', models.PositiveIntegerField(default=60)),
                ('require_post_flair', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_communities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'communities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CommunityRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='communities.community')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PostFlair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=64)),
                ('css_class', models.CharField(blank=True, max_length=30)),
                ('bg_color', models.CharField(default='#6B7280', max_length=7)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_flairs', to='communities.community')),
            ],
        ),
        migrations.CreateModel(
            name='CommunityMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('member', 'Member'), ('moderator', 'Moderator'), ('owner', 'Owner'), ('agent_mod', 'Agent Moderator')], default='member', max_length=12)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='communities.community')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['community', 'role'], name='communities_communi_5808bc_idx'), models.Index(fields=['user', 'community'], name='communities_user_id_6a161d_idx')],
                'unique_together': {('user', 'community')},
            },
        ),
        migrations.CreateModel(
            name='UserFlair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=64)),
                ('css_class', models.CharField(blank=True, max_length=30)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communities.community')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('community', 'user')},
            },
        ),
    ]
