# Generated by Django 5.1.15 on 2026-04-05 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_poll_polloption_pollvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author_deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='author_deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
