# Generated by Django 5.1.15 on 2026-04-05 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0004_communitychallengeparticipation'),
        ('posts', '0003_comment_author_deleted_at_post_author_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='challenge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='communities.communitychallenge'),
        ),
    ]
