# Generated by Django 5.1.15 on 2026-04-06 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_challenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='award_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='award_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
